#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# copyright: 2020-2022, Frederico Martins
# author: Frederico Martins <http://github.com/fscm>
# license: SPDX-License-Identifier: MIT

# pylint: disable=invalid-name,line-too-long
"""Currency generator.

Creates specific versions of Currency based on the info present on the
`currency.csv` file.

Simple usage example:

    ./generator

The `currency.csv` file format is one currency per line with the details
separated by a coma (',') and in the following order:

    * "Currency"
    * "Symbol"
    * "Digital Code"
    * "Class"
    * "Name"
    * "Country"
    * "Format"
    * "Convertion"

`currency.csv` file example:

    "Currency","Symbol","Localized Symbol","Digital Code","Class","Name","Country","Format","Convertion"
    "BDT","৳","৳","050","Taka","Taka","Bangladesh","2.,3%a%s","০১২৩৪৫৬৭৮৯-,."
    "EUR","€","€","978","Euro","Euro","","2,.3%a\u00A0%s",""
    "USD","$","US$","840","Dollar","US Dollar","United States of America","2.,3%-%s%u",""
"""

import csv
import re
import os
import sys
from dataclasses import dataclass
from typing import Final, Tuple
from decimal import Decimal
from re import (
    escape as _escape,
    compile as _compile,
    match as _match,
    sub as _sub)
from mako.template import Template


WORKDIR: Final[str] = os.path.dirname(os.path.realpath(__file__))
DATADIR: Final[str] = os.path.join(WORKDIR, 'data')
TEMPLATESDIR: Final[str] = os.path.join(WORKDIR, 'templates')
CURDIR: Final[str] = os.getcwd()
#OUTPUTDIR: Final[str] = os.path.join(CURDIR, 'output')
OUTPUTDIR: Final[str] = os.path.join(WORKDIR, 'output')
CURRENCIESDIR: Final[str] = os.path.join(OUTPUTDIR, 'currencies')
TESTSDIR: Final[str] = os.path.join(OUTPUTDIR, 'test_currencies')

DATAFILE: Final[str] = os.path.join(DATADIR, 'currency.csv')
INITFILE: Final[str] = os.path.join(TEMPLATESDIR, '__init__.mako')
MODULEFILE: Final[str] = os.path.join(TEMPLATESDIR, 'currency.mako')
TESTFILE: Final[str] = os.path.join(TEMPLATESDIR, 'test.mako')

TEST_CUSTOM_VALUES: Tuple[int] = (1_000, -1_000)
TEST_DEFAULT_VALUES: Tuple[object] = (
    '3.14', 3.14, 10, Decimal(10), '-3.14', -3.14, -10, Decimal(-10))


@dataclass(frozen=True, slots=True)
class T:
    """Currency tests data."""
    test_default: Tuple[str]
    test_custom: Tuple[str]


@dataclass(frozen=True, slots=True)
class E:
    """Currency example."""
    value: float
    variable: str
    output: str
    docstring: Tuple[str]


@dataclass(frozen=False, slots=True)
class C:
    """Currency data representation."""
    alpha_code: str
    class_name: str
    class_lname: str
    convertion: str
    country: str
    main_class: str
    name: str
    numeric_code: str
    pattern: str
    symbol: str
    localized_symbol: str
    example: E
    tests: T


def _format(value, pattern, data) -> str:
    """_format method.
    Args:
        value (Union[str, int, float, Decimal]): Value.
        pattern (str): Formating specifications.
        data (C): Currency data representation.

    Returns:
        str: Formated value.
    """
    value = Decimal(str(value))
    pattern = pattern.encode().decode('unicode_escape')
    data_pattern = data.pattern.encode().decode('unicode_escape')
    regxpr = (
        r'^(?P<decimal_places>\d+)?'
        r'(?P<decimal_sign>[^\d%])?'
        r'(?P<grouping_sign>[^\d%])?'
        r'(?P<grouping_places>\d+)?'
        r'(?P<format>.+)?$')
    values = _match(regxpr, data_pattern).groupdict()
    matches = _match(regxpr, pattern.strip())
    new_values = {k: v for k, v in matches.groupdict().items() if v}
    values = {**values, **new_values}
    decimal_places = int(values['decimal_places'])
    decimal_sign = values['decimal_sign']
    grouping_sign = values['grouping_sign']
    grouping_places = int(values['grouping_places'])
    currency_format = values['format']
    rounded = str(round(value, decimal_places))
    parts = rounded.split('.')
    parts[0] = _sub(
        rf'(\d)(?=(\d{{{grouping_places or -1}}})+$)',
        r'\1,',
        f'{parts[0]}')
    amount = '.'.join(parts)
    converted = amount
    if data.convertion:
        translator = dict(zip('0123456789-', data.convertion))
        converted = ''.join([translator.get(c, c) for c in converted])
    converted = converted.replace('.', 'X').replace(
        ',', grouping_sign).replace('X', decimal_sign)
    sign = '-' * value.is_signed()
    amount_unsign = amount.lstrip('-')
    converted_unsign = converted.lstrip('-')
    rep = {
        '%s': data.symbol,
        '%S': data.localized_symbol,
        '%c': data.alpha_code,
        '%a': converted,
        '%A': amount,
        '%u': converted_unsign,
        '%U': amount_unsign,
        '%-': sign,
        '%%': '%'}
    rep = dict((_escape(k), v) for k, v in rep.items())
    fmt = _compile('|'.join(rep.keys()))
    return fmt.sub(lambda m: rep[_escape(m.group(0))], currency_format)


def _international(value, data) -> str:
    """_international method.

    Args:
        value (Union[str, int, float, Decimal]): Value.
        data (C): Currency data representation.

    Returns:
        str: Formated value.
    """
    value = Decimal(str(value))
    regxpr = (
        r'^(?P<decimal_places>\d+)?'
        r'(?P<decimal_sign>[^\d%])?'
        r'(?P<grouping_sign>[^\d%])?'
        r'(?P<grouping_places>\d+)?'
        r'(?P<format>.+)?$')
    values = _match(regxpr, data.pattern).groupdict()
    parts = str(round(value, int(values['decimal_places']))).split('.')
    parts[0] = _sub(r'(\d)(?=(\d{3})+$)', r'\1,', f'{parts[0]}')
    amount = '.'.join(parts)
    return f'{amount} {data.alpha_code}'


def main() -> None:
    """main method"""
    init_tmpl = Template(filename=INITFILE)
    module_tmpl = Template(filename=MODULEFILE)
    test_tmpl = Template(filename=TESTFILE)

    re_nospace = dict(
        (re.escape(k), v) for k, v in {' ': '', '’': '', '\'': ''}.items())
    re_underscore = dict(
        (re.escape(k), v) for k, v in {' ': '_', '’': '', '\'': ''}.items())
    comp_nospace = re.compile('|'.join(re_nospace.keys()))
    comp_underscore = re.compile('|'.join(re_underscore.keys()))

    crypto_currencies = {}
    currencies = {}

    print('Loading CSV data...')
    with open(DATAFILE, mode='r', encoding='utf-8') as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        headers = [
            f'{h.lower().replace(" ", "_")}' for h in next(csv_reader, None)]

        for record in csv_reader:
            if len(record) == 0:
                continue
            currency = dict(zip(headers, record))
            c = C(
                alpha_code = currency['currency'],
                class_name = comp_nospace.sub(
                    lambda l: re_nospace[re.escape(l.group(0))],
                    currency['name']),
                class_lname = comp_underscore.sub(
                    lambda l: re_underscore[re.escape(l.group(0))],
                    currency['name'].lower()),
                convertion = currency['convertion'],
                country = currency['country'],
                main_class = currency['class'],
                name = currency['name'],
                numeric_code = currency['digital_code'],
                pattern = currency['format'],
                symbol = currency['symbol'],
                localized_symbol = currency['localized_symbol'],
                example=None,
                tests = None)
            c.tests = T(
                test_default = tuple(
                    str((v, str(v), _format(v, currency['format'], c)))
                    for v in TEST_DEFAULT_VALUES),
                test_custom = tuple(
                    str((v, _format(v, r'5,.2%s%u%-', c)))
                    for v in TEST_CUSTOM_VALUES))
            c.example = E(
                value=123456.789,
                variable=c.class_lname,
                output=_format(123456.789, currency['format'], c),
                docstring=(_format(123456.789, c.pattern.replace('%s', '%S'), c), _international(123456.789, c)))
            module = comp_underscore.sub(
                lambda l: re_underscore[re.escape(l.group(0))],
                currency['class'].lower())
            if module == 'crypto':
                i = crypto_currencies.setdefault(
                    module,
                    {'name': currency['class'], 'currencies': []})
            else:
                i = currencies.setdefault(
                    module,
                    {'name': currency['class'], 'currencies': []})
            i['currencies'].append(c)

    print('Creating currency types...')
    if not os.path.exists(CURRENCIESDIR):
        os.makedirs(CURRENCIESDIR)
    for module, info in {**currencies, **crypto_currencies}.items():
        out_text = module_tmpl.render(
            module_name=info['name'],
            currencies=info['currencies'])
        with open(
                os.path.join(CURRENCIESDIR, f'{module}.py'),
                mode='w+',
                encoding='utf-8') as file_out:
            file_out.write(out_text)
            file_out.truncate()
    out_text = init_tmpl.render(currencies={**currencies, **crypto_currencies})
    with open(
            os.path.join(CURRENCIESDIR, '__init__.py'),
            mode='w+',
            encoding='utf-8') as file_out:
        file_out.write(out_text)
        file_out.truncate()

    print('Creating currency tests...')
    if not os.path.exists(TESTSDIR):
        os.makedirs(TESTSDIR)
    for module, info in {**currencies, **crypto_currencies}.items():
        _class_list = [c.class_name for c in info['currencies']]
        if len(_class_list) > 1:
            class_list = '(\n    ' + ',\n    '.join(_class_list) + ')'
        else:
            class_list = _class_list[0]
        out_text = test_tmpl.render(
            module_name=info['name'],
            module_lname=module,
            currencies=info['currencies'],
            class_list=class_list)
        with open(
                os.path.join(TESTSDIR, f'test_{module}.py'),
                mode='w+',
                encoding='utf-8') as file_out:
            file_out.write(out_text)
            file_out.truncate()
    open(
        os.path.join(TESTSDIR, '__init__.py'),
        mode='w+',
        encoding='utf-8').close()







#     out_text = re.sub(
#         '__CURRENCY_MODULE__',
#         currency_info['name'], text_module)
#     for _, values in currency_info['currencies'].items():
#         re_values = dict((re.escape(k), v) for k, v in values.items())
#         comp_values = re.compile('|'.join(re_values.keys()))
#         out_text = out_text + comp_values.sub(
#             lambda l: re_values[re.escape(l.group(0))], # pylint: disable=cell-var-from-loop
#             text_class)
#     with open(
#             f'{workfolder}/_multicurrency/{currency_module}.py',
#             mode='w+',
#             encoding='utf-8') as file_out:
#         _ = file_out.write(out_text)
#         _ = file_out.truncate()
# for currency_module, currency_info in crypto_currencies.items():
#     out_text = re.sub(
#         '__CURRENCY_MODULE__',
#         currency_info['name'], text_module)
#     for _, values in currency_info['currencies'].items():
#         re_values = dict((re.escape(k), v) for k, v in values.items())
#         comp_values = re.compile('|'.join(re_values.keys()))
#         out_text = out_text + comp_values.sub(
#             lambda l: re_values[re.escape(l.group(0))], # pylint: disable=cell-var-from-loop
#             text_class)
#     with open(
#             f'{workfolder}/_multicurrency/{currency_module}.py',
#             mode='w+',
#             encoding='utf-8') as file_out:
#         _ = file_out.write(out_text)
#         _ = file_out.truncate()


if __name__ == '__main__':
    sys.exit(main())


# decimal = CONTEXT.create_decimal(1) / CONTEXT.create_decimal(7)
# example = CONTEXT.create_decimal('123456.789')
# negative = CONTEXT.create_decimal('-100')
# custom = CONTEXT.create_decimal('1000')
# currencies = {}
# crypto_currencies = {}
# countries = {}
# text_module = ''
# text_class = ''
# text_tests = ''


# print('Loading CSV data...')
# with open(f'{workfolder}/{CSV_FILE}', mode='r', encoding='utf-8') as csv_file:
#     csv_reader = csv.reader(csv_file, delimiter=',')
#     headers = [
#         f'{h.lower().replace(" ", "_")}' for h in next(csv_reader, None)]
#     for record in csv_reader:
#         if len(record) == 0:
#             continue
#         currency = dict(zip(headers, record))
#         currency_class = comp_underscore.sub(
#             lambda l: re_nospace[re.escape(l.group(0))],
#             currency['name'])
#         currency_module = comp_underscore.sub(
#             lambda l: re_underscore[re.escape(l.group(0))],
#             currency['class'].lower())
#         currency_variable = comp_underscore.sub(
#             lambda l: re_underscore[re.escape(l.group(0))],
#             currency['name'].lower())
#         decimal_zeros = '0' * int(currency['decimal_places'])
#         decimal_sign = f'{currency["decimal_sign"]}' if int(currency['decimal_places']) else ''
#         decimal_part = f'{decimal_sign}{decimal_zeros}'
#         grouping_sign_alt = f'\\{currency["grouping_sign"]}' if currency[
#             'grouping_sign'] == '\'' else f'{currency["grouping_sign"]}'
#         symbol_ahead = currency['symbol_ahead'] == 'True'
#         _ = countries.setdefault(
#             currency['country'],
#             (currency['name'], f'{currency_module}.{currency_class}'))
#         if currency_module == 'crypto':
#             t = crypto_currencies.setdefault(
#                 currency_module,
#                 {'name': currency['class'], 'currencies': {}})
#         else:
#             t = currencies.setdefault(
#                 currency_module,
#                 {'name': currency['class'], 'currencies': {}})
#         _ = t['currencies'].setdefault(currency_variable, {
#             '__CODE__': currency['digital_code'],
#             '__CURRENCY__': currency['currency'],
#             '__CURRENCY_CLASS__': currency_class,
#             '__CURRENCY_NAME__': currency['name'],
#             '__CURRENCY_VARIABLE__': currency_variable,
#             '__DECIMAL_PART__': decimal_part,
#             '__DECIMAL_PLACES__': currency['decimal_places'],
#             '__DECIMAL_SIGN__': currency['decimal_sign'],
#             '__DECIMAL_SIGN_STR__': bytes(
#                 currency['decimal_sign'], 'utf-8').decode('unicode_escape'),
#             '__GROUPING_PLACES__': currency['grouping_places'],
#             '__GROUPING_SIGN__': currency['grouping_sign'],
#             '__GROUPING_SIGN_STR__': bytes(
#                 currency['grouping_sign'], 'utf-8').decode('unicode_escape'),
#             '__GROUPING_SIGN_ALT__': grouping_sign_alt,
#             '__SYMBOL__': currency['symbol'],
#             '__SYMBOL_SEPARATOR__': currency['symbol_separator'],
#             '__SYMBOL_SEPARATOR_STR__': bytes(
#                 currency['symbol_separator'], 'utf-8').decode('unicode_escape'),
#             '__SYMBOL_AHEAD__': currency['symbol_ahead'],
#             '__SYMBOL_AHEAD_ALT__': '' if symbol_ahead else 'not ',
#             '__LOCALIZED_SYMBOL__': currency['localized_symbol'],
#             '__EXAMPLE_OUTPUT__': _format(
#                 example,
#                 int(currency['decimal_places']),
#                 int(currency['grouping_places']),
#                 currency['currency'],
#                 currency['grouping_sign'],
#                 currency['decimal_sign'],
#                 currency['symbol'],
#                 symbol_ahead,
#                 currency['symbol_separator'],
#                 currency['localized_symbol'],
#                 currency['convertion']),
#             '__EXAMPLE_1DIV7__': _format(
#                 decimal,
#                 int(currency['decimal_places']),
#                 int(currency['grouping_places']),
#                 currency['currency'],
#                 currency['grouping_sign'],
#                 currency['decimal_sign'],
#                 currency['symbol'],
#                 symbol_ahead,
#                 currency['symbol_separator'],
#                 currency['localized_symbol'],
#                 currency['convertion']),
#             '__EXAMPLE_NEGATIVE__': _format(
#                 negative,
#                 int(currency['decimal_places']),
#                 int(currency['grouping_places']),
#                 currency['currency'],
#                 currency['grouping_sign'],
#                 currency['decimal_sign'],
#                 currency['symbol'],
#                 symbol_ahead,
#                 currency['symbol_separator'],
#                 currency['localized_symbol'],
#                 currency['convertion']),
#             '__EXAMPLE_CUSTOM__': _format(
#                 custom,
#                 5,
#                 2,
#                 currency['currency'],
#                 currency['decimal_sign'],
#                 grouping_sign_alt,
#                 currency['symbol'],
#                 False,
#                 '_',
#                 currency['localized_symbol'],
#                 '',
#                 True,
#                 False),
#             '__EXAMPLE_LOCALIZED__': _format(
#                 example,
#                 int(currency['decimal_places']),
#                 int(currency['grouping_places']),
#                 currency['currency'],
#                 currency['grouping_sign'],
#                 currency['decimal_sign'],
#                 currency['symbol'],
#                 symbol_ahead,
#                 currency['symbol_separator'],
#                 currency['localized_symbol'],
#                 currency['convertion'],
#                 False,
#                 True),
#             '__CONVERTION__': currency['convertion']})


# print('Creating currency types...')
# for currency_module, currency_info in currencies.items():
#     out_text = re.sub(
#         '__CURRENCY_MODULE__',
#         currency_info['name'], text_module)
#     for _, values in currency_info['currencies'].items():
#         re_values = dict((re.escape(k), v) for k, v in values.items())
#         comp_values = re.compile('|'.join(re_values.keys()))
#         out_text = out_text + comp_values.sub(
#             lambda l: re_values[re.escape(l.group(0))], # pylint: disable=cell-var-from-loop
#             text_class)
#     with open(
#             f'{workfolder}/_multicurrency/{currency_module}.py',
#             mode='w+',
#             encoding='utf-8') as file_out:
#         _ = file_out.write(out_text)
#         _ = file_out.truncate()
# for currency_module, currency_info in crypto_currencies.items():
#     out_text = re.sub(
#         '__CURRENCY_MODULE__',
#         currency_info['name'], text_module)
#     for _, values in currency_info['currencies'].items():
#         re_values = dict((re.escape(k), v) for k, v in values.items())
#         comp_values = re.compile('|'.join(re_values.keys()))
#         out_text = out_text + comp_values.sub(
#             lambda l: re_values[re.escape(l.group(0))], # pylint: disable=cell-var-from-loop
#             text_class)
#     with open(
#             f'{workfolder}/_multicurrency/{currency_module}.py',
#             mode='w+',
#             encoding='utf-8') as file_out:
#         _ = file_out.write(out_text)
#         _ = file_out.truncate()


# print('Creating currency tests...')
# for currency_module, currency_info in currencies.items():
#     out_text = re.sub(
#         '__CURRENCY_MODULE__',
#         currency_info['name'], text_test_module)
#     currency_class_list = []
#     for currency, values in currency_info['currencies'].items():
#         currency_class_list.append(values['__CURRENCY_CLASS__'])
#         re_values = dict((re.escape(k), v) for k, v in values.items())
#         comp_values = re.compile('|'.join(re_values.keys()))
#         out_text = out_text + comp_values.sub(
#             lambda l: re_values[re.escape(l.group(0))],  # pylint: disable=cell-var-from-loop
#             text_test_class)
#         out_text = re.sub('__CURRENCY_MODULE__', currency_module, out_text)
#     if len(currency_class_list) > 1:
#         __CURRENCY_CLASS_LIST__ = '(\n    ' + ',\n    '.join(currency_class_list) + ')'
#     else:
#         __CURRENCY_CLASS_LIST__ = currency_class_list[0]
#     out_text = re.sub(
#         '__CURRENCY_CLASS_LIST__',
#         __CURRENCY_CLASS_LIST__,
#         out_text)
#     with open(
#             f'{workfolder}/_tests/test_{currency_module}.py',
#             mode='w+',
#             encoding='utf-8') as file_out:
#         _ = file_out.write(out_text)
#         _ = file_out.truncate()
# for currency_module, currency_info in crypto_currencies.items():
#     out_text = re.sub(
#         '__CURRENCY_MODULE__',
#         currency_info['name'], text_test_module)
#     currency_class_list = []
#     for currency, values in currency_info['currencies'].items():
#         currency_class_list.append(values['__CURRENCY_CLASS__'])
#         re_values = dict((re.escape(k), v) for k, v in values.items())
#         comp_values = re.compile('|'.join(re_values.keys()))
#         out_text = out_text + comp_values.sub(
#             lambda l: re_values[re.escape(l.group(0))],  # pylint: disable=cell-var-from-loop
#             text_test_class)
#         out_text = re.sub('__CURRENCY_MODULE__', currency_module, out_text)
#     if len(currency_class_list) > 1:
#         __CURRENCY_CLASS_LIST__ = '(\n    ' + ',\n    '.join(currency_class_list) + ')'
#     else:
#         __CURRENCY_CLASS_LIST__ = currency_class_list[0]
#     out_text = re.sub(
#         '__CURRENCY_CLASS_LIST__',
#         __CURRENCY_CLASS_LIST__,
#         out_text)
#     with open(
#             f'{workfolder}/_tests/test_{currency_module}.py',
#             mode='w+',
#             encoding='utf-8') as file_out:
#         _ = file_out.write(out_text)
#         _ = file_out.truncate()


# print()
# print('Generating __init__.py file data...')
# all_classes = []
# all_crypto_classes = []

# print()
# print('Imports:')
# for currency_module, data in sorted({**currencies, **crypto_currencies}.items()):
#     classes = [data['currencies'][c]['__CURRENCY_CLASS__'] for c in data['currencies']]
#     if len(classes) > 1:
#         print(f'from .{currency_module} import (')
#         print('    ' + ',\n    '.join(classes) + ')')
#     else:
#         print(f'from .{currency_module} import {classes[0]}')
#     if currency_module == 'crypto':
#         all_crypto_classes.extend(classes)
#     else:
#         all_classes.extend(classes)
# print()
# print('__all__:')
# print('    \'' + '\',\n    \''.join(sorted(all_classes) + sorted(all_crypto_classes)) + '\']')

# print()
# print('docstring supported currencies:')
# supported = []
# for currency_module, data in currencies.items():
#     for _, values in data['currencies'].items():
#         currency_class = values['__CURRENCY_CLASS__']
#         eg_locale = values['__EXAMPLE_OUTPUT__']
#         eg_localized = values['__EXAMPLE_LOCALIZED__']
#         eg_international = _format(
#                 example, int(values['__DECIMAL_PLACES__']),
#                 int(values['__GROUPING_PLACES__']),
#                 values['__CURRENCY__'], '', '', '', False, '', '', '', True)
#         supported.append((
#             currency_class, (
#             f'* `multicurrency.{currency_module}.{currency_class}` ({eg_locale} | {eg_localized} | {eg_international})',
#             f'* `{currency_class}` ({eg_locale} | {eg_localized} | {eg_international})')))
# supported_sorted = [c[0] for _, c in sorted(supported)]
# print(',\n'.join(supported_sorted))

# print()
# print('docstring supported crypto currencies:')
# supported_crypto = []
# for currency_module, data in crypto_currencies.items():
#     for _, values in data['currencies'].items():
#         currency_class = values['__CURRENCY_CLASS__']
#         eg_locale = values['__EXAMPLE_OUTPUT__']
#         eg_localized = values['__EXAMPLE_LOCALIZED__']
#         eg_international = _format(
#                 example, int(values['__DECIMAL_PLACES__']),
#                 int(values['__GROUPING_PLACES__']),
#                 values['__CURRENCY__'], '', '', '', False, '', '', '', True)
#         supported_crypto.append((
#             currency_class, (
#             f'* `multicurrency.{currency_module}.{currency_class}` ({eg_locale} | {eg_localized} | {eg_international})',
#             f'* `{currency_class}` ({eg_locale} | {eg_localized} | {eg_international})')))
# supported_crypto_sorted = [c[0] for _, c in sorted(supported_crypto)]
# print(',\n'.join(supported_crypto_sorted))

# print()
# print('Generating README.txt file data...')

# print()
# print('readme supported currencies:')
# supported_sorted = [c[1] for _, c in sorted(supported)]
# print(',\n'.join(supported_sorted))
# print()

# print()
# print('readme supported crypto currencies:')
# supported_crypto_sorted = [c[1] for _, c in sorted(supported_crypto)]
# print(',\n'.join(supported_crypto_sorted))
# print()

# pylint: enable=invalid-name,line-too-long
