from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class UAEDirham(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> UAEDirham: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> UAEDirham: ...

class MoroccanDirham(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> MoroccanDirham: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> MoroccanDirham: ...
