from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Self

class AustralianDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class AustralianDollarAU(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class AustralianDollarKI(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class AustralianDollarCC(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class AustralianDollarMR(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class AustralianDollarTV(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class BarbadosDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class BermudianDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class BruneiDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class BruneiDollarBN(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class BruneiDollarSG(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class BahamianDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class BelizeDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CanadianDollarEN(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CanadianDollarFR(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class FijiDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class GuyanaDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class HongKongDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class JamaicanDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CaymanIslandsDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class LiberianDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class NamibiaDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class NewZealandDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class NewZealandDollarCK(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class NewZealandDollarNZ(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class NewZealandDollarNU(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class NewZealandDollarPN(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SolomonIslandsDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SingaporeDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SingaporeDollarBN(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SingaporeDollarSG(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SurinameDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class TrinidadandTobagoDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class TaiwanDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarAS(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarIO(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarVG(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarGU(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarHT(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarMH(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarFM(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarMP(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarPC(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarPW(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarPA(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarPR(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarTC(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class USDollarVI(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class EasternCaribbeanDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class EasternCaribbeanDollarAI(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class EasternCaribbeanDollarAG(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class EasternCaribbeanDollarDM(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class EasternCaribbeanDollarGD(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class EasternCaribbeanDollarMS(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class EasternCaribbeanDollarKN(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class EasternCaribbeanDollarLC(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class EasternCaribbeanDollarVC(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class ZimbabweDollar(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...
