from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class AustralianDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> AustralianDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> AustralianDollar: ...

class AustralianDollarAU(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> AustralianDollarAU: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> AustralianDollarAU: ...

class AustralianDollarKI(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> AustralianDollarKI: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> AustralianDollarKI: ...

class AustralianDollarCC(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> AustralianDollarCC: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> AustralianDollarCC: ...

class AustralianDollarMR(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> AustralianDollarMR: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> AustralianDollarMR: ...

class AustralianDollarTV(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> AustralianDollarTV: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> AustralianDollarTV: ...

class BarbadosDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> BarbadosDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> BarbadosDollar: ...

class BermudianDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> BermudianDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> BermudianDollar: ...

class BruneiDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> BruneiDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> BruneiDollar: ...

class BruneiDollarBN(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> BruneiDollarBN: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> BruneiDollarBN: ...

class BruneiDollarSG(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> BruneiDollarSG: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> BruneiDollarSG: ...

class BahamianDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> BahamianDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> BahamianDollar: ...

class BelizeDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> BelizeDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> BelizeDollar: ...

class CanadianDollarEN(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CanadianDollarEN: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CanadianDollarEN: ...

class CanadianDollarFR(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CanadianDollarFR: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CanadianDollarFR: ...

class FijiDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> FijiDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> FijiDollar: ...

class GuyanaDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> GuyanaDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> GuyanaDollar: ...

class HongKongDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> HongKongDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> HongKongDollar: ...

class JamaicanDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> JamaicanDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> JamaicanDollar: ...

class CaymanIslandsDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CaymanIslandsDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CaymanIslandsDollar: ...

class LiberianDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> LiberianDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> LiberianDollar: ...

class NamibiaDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> NamibiaDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> NamibiaDollar: ...

class NewZealandDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> NewZealandDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> NewZealandDollar: ...

class NewZealandDollarCK(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> NewZealandDollarCK: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> NewZealandDollarCK: ...

class NewZealandDollarNZ(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> NewZealandDollarNZ: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> NewZealandDollarNZ: ...

class NewZealandDollarNU(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> NewZealandDollarNU: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> NewZealandDollarNU: ...

class NewZealandDollarPN(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> NewZealandDollarPN: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> NewZealandDollarPN: ...

class SolomonIslandsDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SolomonIslandsDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SolomonIslandsDollar: ...

class SingaporeDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SingaporeDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SingaporeDollar: ...

class SingaporeDollarBN(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SingaporeDollarBN: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SingaporeDollarBN: ...

class SingaporeDollarSG(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SingaporeDollarSG: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SingaporeDollarSG: ...

class SurinameDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SurinameDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SurinameDollar: ...

class TrinidadandTobagoDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> TrinidadandTobagoDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> TrinidadandTobagoDollar: ...

class TaiwanDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> TaiwanDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> TaiwanDollar: ...

class USDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollar: ...

class USDollarAS(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarAS: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarAS: ...

class USDollarIO(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarIO: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarIO: ...

class USDollarVG(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarVG: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarVG: ...

class USDollarGU(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarGU: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarGU: ...

class USDollarHT(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarHT: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarHT: ...

class USDollarMH(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarMH: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarMH: ...

class USDollarFM(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarFM: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarFM: ...

class USDollarMP(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarMP: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarMP: ...

class USDollarPC(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarPC: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarPC: ...

class USDollarPW(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarPW: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarPW: ...

class USDollarPA(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarPA: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarPA: ...

class USDollarPR(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarPR: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarPR: ...

class USDollarTC(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarTC: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarTC: ...

class USDollarVI(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> USDollarVI: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> USDollarVI: ...

class EasternCaribbeanDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EasternCaribbeanDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EasternCaribbeanDollar: ...

class EasternCaribbeanDollarAI(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EasternCaribbeanDollarAI: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EasternCaribbeanDollarAI: ...

class EasternCaribbeanDollarAG(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EasternCaribbeanDollarAG: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EasternCaribbeanDollarAG: ...

class EasternCaribbeanDollarDM(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EasternCaribbeanDollarDM: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EasternCaribbeanDollarDM: ...

class EasternCaribbeanDollarGD(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EasternCaribbeanDollarGD: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EasternCaribbeanDollarGD: ...

class EasternCaribbeanDollarMS(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EasternCaribbeanDollarMS: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EasternCaribbeanDollarMS: ...

class EasternCaribbeanDollarKN(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EasternCaribbeanDollarKN: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EasternCaribbeanDollarKN: ...

class EasternCaribbeanDollarLC(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EasternCaribbeanDollarLC: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EasternCaribbeanDollarLC: ...

class EasternCaribbeanDollarVC(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EasternCaribbeanDollarVC: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EasternCaribbeanDollarVC: ...

class ZimbabweDollar(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> ZimbabweDollar: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> ZimbabweDollar: ...
