from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class Euro(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> Euro: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> Euro: ...

class EuroSBA(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroSBA: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroSBA: ...

class EuroAD(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroAD: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroAD: ...

class EuroAT(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroAT: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroAT: ...

class EuroBE(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroBE: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroBE: ...

class EuroCY(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroCY: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroCY: ...

class EuroEE(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroEE: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroEE: ...

class EuroFI(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroFI: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroFI: ...

class EuroFR(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroFR: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroFR: ...

class EuroDE(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroDE: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroDE: ...

class EuroGR(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroGR: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroGR: ...

class EuroIE(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroIE: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroIE: ...

class EuroIT(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroIT: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroIT: ...

class EuroXK(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroXK: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroXK: ...

class EuroLV(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroLV: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroLV: ...

class EuroLT(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroLT: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroLT: ...

class EuroLU(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroLU: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroLU: ...

class EuroMT(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroMT: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroMT: ...

class EuroMC(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroMC: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroMC: ...

class EuroME(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroME: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroME: ...

class EuroNL(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroNL: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroNL: ...

class EuroPT(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroPT: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroPT: ...

class EuroSM(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroSM: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroSM: ...

class EuroSK(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroSK: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroSK: ...

class EuroSI(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroSI: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroSI: ...

class EuroES(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroES: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroES: ...

class EuroVA(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> EuroVA: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> EuroVA: ...
