from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Self, Union

class Euro(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroSBA(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroAD(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroAT(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroBE(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroCY(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroEE(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroFI(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroFR(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroDE(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroGR(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroIE(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroIT(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroXK(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroLV(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroLT(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroLU(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroMT(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroMC(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroME(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroNL(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroPT(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroSM(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroSK(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroSI(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroES(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class EuroVA(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...
