from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Self

class BurundiFranc(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CongoleseFranc(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SwissFranc(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SwissFrancLI(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SwissFrancCH(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class DjiboutiFranc(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class GuineaFranc(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class RwandaFranc(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBEAC(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBEACCM(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBEACCF(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBEACTD(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBEACCD(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBEACGQ(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBEACGA(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBCEAO(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBCEAOBJ(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBCEAOBF(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBCEAOCI(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBCEAOGW(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBCEAOML(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBCEAONG(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBCEAOSN(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFAFrancBCEAOTG(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFPFranc(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFPFrancPF(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFPFrancNC(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class CFPFrancWF(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...
