from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class BurundiFranc(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> BurundiFranc: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> BurundiFranc: ...

class CongoleseFranc(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CongoleseFranc: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CongoleseFranc: ...

class SwissFranc(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SwissFranc: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SwissFranc: ...

class SwissFrancLI(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SwissFrancLI: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SwissFrancLI: ...

class SwissFrancCH(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SwissFrancCH: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SwissFrancCH: ...

class DjiboutiFranc(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> DjiboutiFranc: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> DjiboutiFranc: ...

class GuineaFranc(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> GuineaFranc: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> GuineaFranc: ...

class RwandaFranc(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> RwandaFranc: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> RwandaFranc: ...

class CFAFrancBEAC(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBEAC: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBEAC: ...

class CFAFrancBEACCM(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBEACCM: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBEACCM: ...

class CFAFrancBEACCF(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBEACCF: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBEACCF: ...

class CFAFrancBEACTD(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBEACTD: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBEACTD: ...

class CFAFrancBEACCD(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBEACCD: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBEACCD: ...

class CFAFrancBEACGQ(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBEACGQ: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBEACGQ: ...

class CFAFrancBEACGA(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBEACGA: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBEACGA: ...

class CFAFrancBCEAO(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBCEAO: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBCEAO: ...

class CFAFrancBCEAOBJ(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBCEAOBJ: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBCEAOBJ: ...

class CFAFrancBCEAOBF(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBCEAOBF: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBCEAOBF: ...

class CFAFrancBCEAOCI(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBCEAOCI: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBCEAOCI: ...

class CFAFrancBCEAOGW(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBCEAOGW: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBCEAOGW: ...

class CFAFrancBCEAOML(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBCEAOML: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBCEAOML: ...

class CFAFrancBCEAONG(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBCEAONG: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBCEAONG: ...

class CFAFrancBCEAOSN(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBCEAOSN: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBCEAOSN: ...

class CFAFrancBCEAOTG(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFAFrancBCEAOTG: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFAFrancBCEAOTG: ...

class CFPFranc(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFPFranc: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFPFranc: ...

class CFPFrancPF(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFPFrancPF: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFPFrancPF: ...

class CFPFrancNC(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFPFrancNC: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFPFrancNC: ...

class CFPFrancWF(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CFPFrancWF: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CFPFrancWF: ...
