from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class IcelandKrona(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> IcelandKrona: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> IcelandKrona: ...

class SwedishKrona(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SwedishKrona: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SwedishKrona: ...
