from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class DanishKrone(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> DanishKrone: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> DanishKrone: ...

class NorwegianKrone(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> NorwegianKrone: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> NorwegianKrone: ...
