from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class Kwacha(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> Kwacha: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> Kwacha: ...

class ZambianKwacha(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> ZambianKwacha: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> ZambianKwacha: ...
