from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class Lari(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> Lari: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> Lari: ...

class GeorgiaLari(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> GeorgiaLari: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> GeorgiaLari: ...

class SouthOssetiaLari(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SouthOssetiaLari: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SouthOssetiaLari: ...
