from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class TurkishLira(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> TurkishLira: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> TurkishLira: ...

class TurkishLiraCY(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> TurkishLiraCY: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> TurkishLiraCY: ...

class TurkishLiraTR(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> TurkishLiraTR: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> TurkishLiraTR: ...
