from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class AzerbaijanianManat(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> AzerbaijanianManat: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> AzerbaijanianManat: ...

class Manat(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> Manat: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> Manat: ...
