from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class ArgentinePeso(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> ArgentinePeso: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> ArgentinePeso: ...

class ChileanPeso(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> ChileanPeso: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> ChileanPeso: ...

class ColombianPeso(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> ColombianPeso: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> ColombianPeso: ...

class CubanPeso(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> CubanPeso: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> CubanPeso: ...

class DominicanPeso(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> DominicanPeso: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> DominicanPeso: ...

class MexicanPeso(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> MexicanPeso: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> MexicanPeso: ...

class PhilippinePeso(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> PhilippinePeso: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> PhilippinePeso: ...

class PesoUruguayo(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> PesoUruguayo: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> PesoUruguayo: ...
