from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Self

class EgyptianPound(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class FalklandIslandsPound(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class PoundSterling(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class PoundSterlingGG(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class PoundSterlingIO(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class PoundSterlingGB(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class PoundSterlingIM(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class GibraltarPound(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class LebanesePound(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SudanesePound(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SaintHelenaPoundAI(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SaintHelenaPound(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SaintHelenaPoundTC(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...

class SyrianPound(Currency):
    def __new__(cls, amount: str | float | Decimal, pattern: str | None = ...) -> Self: ...
    def __recreate__(self, amount: str | float | Decimal) -> Self: ...
