from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class Rand(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> Rand: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> Rand: ...

class RandLS(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> RandLS: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> RandLS: ...

class RandNA(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> RandNA: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> RandNA: ...

class RandZA(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> RandZA: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> RandZA: ...
