from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class IranianRial(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> IranianRial: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> IranianRial: ...

class RialOmani(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> RialOmani: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> RialOmani: ...

class QatariRial(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> QatariRial: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> QatariRial: ...

class YemeniRial(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> YemeniRial: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> YemeniRial: ...
