from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Self, Union

class BelarusianRuble(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class RussianRuble(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class RussianRubleRU(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...

class RussianRubleGE(Currency):
    def __new__(cls, amount: Union[str, float, Decimal], pattern: Optional[str] = ...) -> Self: ...
    def __recreate__(self, amount: Union[str, float, Decimal]) -> Self: ...
