from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class BelarusianRuble(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> BelarusianRuble: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> BelarusianRuble: ...

class RussianRuble(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> RussianRuble: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> RussianRuble: ...

class RussianRubleRU(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> RussianRubleRU: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> RussianRubleRU: ...

class RussianRubleGE(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> RussianRubleGE: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> RussianRubleGE: ...
