from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class IndianRupee(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> IndianRupee: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> IndianRupee: ...

class IndianRupeeBT(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> IndianRupeeBT: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> IndianRupeeBT: ...

class IndianRupeeIN(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> IndianRupeeIN: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> IndianRupeeIN: ...

class SriLankaRupee(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SriLankaRupee: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SriLankaRupee: ...

class MauritiusRupee(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> MauritiusRupee: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> MauritiusRupee: ...

class NepaleseRupee(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> NepaleseRupee: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> NepaleseRupee: ...

class PakistanRupee(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> PakistanRupee: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> PakistanRupee: ...

class SeychellesRupee(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SeychellesRupee: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SeychellesRupee: ...
