from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class NewIsraeliShekel(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> NewIsraeliShekel: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> NewIsraeliShekel: ...

class NewIsraeliShekelIL(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> NewIsraeliShekelIL: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> NewIsraeliShekelIL: ...

class NewIsraeliShekelPS(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> NewIsraeliShekelPS: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> NewIsraeliShekelPS: ...
