from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class KenyanShilling(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> KenyanShilling: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> KenyanShilling: ...

class SomaliShilling(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SomaliShilling: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SomaliShilling: ...

class TanzanianShilling(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> TanzanianShilling: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> TanzanianShilling: ...

class UgandaShilling(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> UgandaShilling: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> UgandaShilling: ...
