from decimal import Decimal
from multicurrency.pycurrency import Currency
from typing import Optional, Union

class NorthKoreanWon(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> NorthKoreanWon: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> NorthKoreanWon: ...

class SouthKoreanWon(Currency):
    def __new__(cls, amount: Union[str, int, float, Decimal], pattern: Optional[str] = ...) -> SouthKoreanWon: ...
    def __recreate__(self, amount: Union[str, int, float, Decimal]) -> SouthKoreanWon: ...
