#!/bin/sh
#
# Shell script to run the profile tool.
#
# Copyright 2020-2022, Frederico Martins
#   Author: Frederico Martins <http://github.com/fscm>
#
# SPDX-License-Identifier: MIT
#
# This program is free software. You can use it and/or modify it under the
# terms of the MIT License.
#

set -e

# Variables
OUTPUT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1; pwd -P)"
OUTPUT_FILE="${OUTPUT_DIR}/report.html"
PROFILER='scalene'
#PROFILER_OPTIONS="--cli --html --outfile ${OUTPUT_FILE} --reduced-profile --memory-leak-detector"
PROFILER_OPTIONS="--cli --html --outfile ${OUTPUT_FILE} --reduced-profile"
PROFILER_SCRIPT='profiler'

${PROFILER} ${PROFILER_OPTIONS} "${OUTPUT_DIR}/${PROFILER_SCRIPT}"

exit 0
